# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(739, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_import = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_import.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.pushButton_import.setObjectName("pushButton_import")
        self.label_import_name = QtWidgets.QLabel(self.centralwidget)
        self.label_import_name.setGeometry(QtCore.QRect(120, 15, 241, 21))
        self.label_import_name.setText("")
        self.label_import_name.setObjectName("label_import_name")
        self.label_original_image = QtWidgets.QLabel(self.centralwidget)
        self.label_original_image.setGeometry(QtCore.QRect(10, 90, 361, 361))
        self.label_original_image.setText("")
        self.label_original_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_original_image.setObjectName("label_original_image")
        self.spinBox_n_colours = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_n_colours.setGeometry(QtCore.QRect(550, 30, 42, 22))
        self.spinBox_n_colours.setObjectName("spinBox_n_colours")
        self.label_n_colours = QtWidgets.QLabel(self.centralwidget)
        self.label_n_colours.setGeometry(QtCore.QRect(390, 30, 141, 20))
        self.label_n_colours.setObjectName("label_n_colours")
        self.pushButton_n_colours = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_n_colours.setGeometry(QtCore.QRect(600, 30, 51, 28))
        self.pushButton_n_colours.setObjectName("pushButton_n_colours")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(370, 20, 20, 511))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.listView_choosen_colours = QtWidgets.QListView(self.centralwidget)
        self.listView_choosen_colours.setGeometry(QtCore.QRect(390, 90, 341, 361))
        self.listView_choosen_colours.setObjectName("listView_choosen_colours")
        self.label_2_choosen_colours = QtWidgets.QLabel(self.centralwidget)
        self.label_2_choosen_colours.setGeometry(QtCore.QRect(390, 70, 101, 16))
        self.label_2_choosen_colours.setObjectName("label_2_choosen_colours")
        self.pushButton_go = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_go.setGeometry(QtCore.QRect(540, 520, 93, 28))
        self.pushButton_go.setObjectName("pushButton_go")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(10, 480, 93, 28))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.label_total_number_of_colour = QtWidgets.QLabel(self.centralwidget)
        self.label_total_number_of_colour.setGeometry(QtCore.QRect(390, 10, 191, 16))
        self.label_total_number_of_colour.setObjectName("label_total_number_of_colour")
        self.label_image_generation = QtWidgets.QLabel(self.centralwidget)
        self.label_image_generation.setGeometry(QtCore.QRect(110, 480, 101, 21))
        self.label_image_generation.setText("")
        self.label_image_generation.setObjectName("label_image_generation")
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setGeometry(QtCore.QRect(640, 520, 93, 28))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_delete_colour = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete_colour.setGeometry(QtCore.QRect(640, 460, 93, 28))
        self.pushButton_delete_colour.setObjectName("pushButton_delete_colour")
        self.pushButton_change_colour = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_change_colour.setGeometry(QtCore.QRect(540, 460, 93, 28))
        self.pushButton_change_colour.setObjectName("pushButton_change_colour")
        self.pushButton_add_colour = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_colour.setGeometry(QtCore.QRect(440, 460, 93, 28))
        self.pushButton_add_colour.setObjectName("pushButton_add_colour")
        self.pushButton_add_mouse_colour = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_mouse_colour.setGeometry(QtCore.QRect(300, 480, 61, 28))
        self.pushButton_add_mouse_colour.setObjectName("pushButton_add_mouse_colour")
        self.pushButton_change_mouse_colour = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_change_mouse_colour.setGeometry(QtCore.QRect(300, 510, 61, 28))
        self.pushButton_change_mouse_colour.setObjectName("pushButton_change_mouse_colour")
        self.listView_mouse_colour = QtWidgets.QListView(self.centralwidget)
        self.listView_mouse_colour.setGeometry(QtCore.QRect(220, 480, 71, 21))
        self.listView_mouse_colour.setObjectName("listView_mouse_colour")
        self.pushButton_merge_colours = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_merge_colours.setGeometry(QtCore.QRect(440, 490, 93, 28))
        self.pushButton_merge_colours.setObjectName("pushButton_merge_colours")
        self.spinBox_merge_colours = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_merge_colours.setGeometry(QtCore.QRect(390, 490, 42, 22))
        self.spinBox_merge_colours.setObjectName("spinBox_merge_colours")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 739, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_import.setText(_translate("MainWindow", "Import"))
        self.label_n_colours.setText(_translate("MainWindow", "Final number of colours:"))
        self.pushButton_n_colours.setText(_translate("MainWindow", "Ok"))
        self.label_2_choosen_colours.setText(_translate("MainWindow", "Choosen colours:"))
        self.pushButton_go.setText(_translate("MainWindow", "Go!"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.label_total_number_of_colour.setText(_translate("MainWindow", "Total Number of colours:"))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.pushButton_delete_colour.setText(_translate("MainWindow", "Delete"))
        self.pushButton_change_colour.setText(_translate("MainWindow", "Change colour"))
        self.pushButton_add_colour.setText(_translate("MainWindow", "Add colour"))
        self.pushButton_add_mouse_colour.setText(_translate("MainWindow", "Add"))
        self.pushButton_change_mouse_colour.setText(_translate("MainWindow", "Change"))
        self.pushButton_merge_colours.setText(_translate("MainWindow", "Merge"))

